version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd  Lambda2
      - zip -r -g deployment_package.zip . #
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name Lambda2 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
